### ISSUE TITLE
Mandatory Params

### ISSUE THREAD

**Issue by riweston** [beararmy/strava-tools#10]
Pro-tip! You can write out your params like this to avoid your first if/else statement 

param(
	
	[Parameter(Mandatory=$true)]
	$ActivityID,

	[Parameter(Mandatory=$true)]
	$Direction
)

https://github.com/beararmy/strava-tools/blob/f7ad0ad76361a316aaf2e699d54c929ec33fa6ba/strava.ps1#L31

**Comment by beararmy** [comment]
Thanks Rich, this function has been re-worked, but this has been rolled in.

You're the best.
